# Workfloww de autenticação na infraestrutura da AWS e criação da infraestrutura do EKS (Cluster Kubernetes)

name: EKSInfra

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

env:
  REGION_DEFAULT: us-east-1

jobs:
  deploy:
    name: Deploying using AWS
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Create EKS infrastructure using Terraform
        run: |
         terraform init
         terraform plan
         terraform apply -auto-approve
