# Workfloww de autenticação na infraestrutura da AWS e criação da infraestrutura do EKS (Cluster Kubernetes)

name: EKSInfra

# Controls when the workflow will run
on:
  push:
    branches: 
      - main

env:
  REGION_DEFAULT: us-east-1

jobs:
  deploy:
    name: Deploying using AWS
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Check if S3 bucket exists
        id: check_bucket
        run: |
          BUCKET_NAME="fiap-backend-tf"
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket exists."
            echo "::set-output name=exists::true"
          else
            echo "Bucket does not exist."
            echo "::set-output name=exists::false"
          fi

      - name: Create S3 bucket if it does not exist
        if: steps.check_bucket.outputs.exists == 'false'
        run: |
          aws s3api create-bucket --bucket fiap-backend-tf
          echo "Bucket created." 

      # - name: Create EKS infrastructure using Terraform
      #   run: |
      #    terraform init
      #    terraform plan
      #    terraform apply -auto-approve
